"""
    Colors.
"""


COLORS = [
    'white',
    'blue2',
    'red2',
    'green',
    'DodgerBlue2',
    'purple1',
    'purple4',
    'gold',
    'cyan',
    'green2',
    'yellow',
    'coral',
    'dark salmon',
    'medium orchid',
    'thistle',
    'PeachPuff3',
    'gray',
    'LemonChiffon2',
    'cornsilk4',
    'LavenderBlush2',
    'MistyRose4',
    'SlateBlue4',
    'SteelBlue3',
    'SkyBlue1',
    'LightSkyBlue3',
    'SlateGray4',
    'LightSteelBlue4',
    'LightCyan2',
    'PaleTurquoise3',
    'CadetBlue4',
    'cyan4',
    'aquamarine2',
    'gray',
    'DarkSeaGreen4',
    'PaleGreen3',
    'snow',
    'OliveDrab1',
    'DarkOliveGreen3',
    'LightGoldenrod1',
    'LightYellow2',
    'DarkGoldenrod1',
    'RosyBrown1',
    'IndianRed3',
    'burlywood2',
    'tan2',
    'firebrick3',
    'salmon3',
    'orange3',
    'coral1',
    'OrangeRed3',
    'HotPink1',
    'LightPink1',
    'PaleVioletRed2',
    'maroon3',
    'magenta2',
    'plum2',
    'MediumOrchid4',
    'MediumPurple3',
]

STATE_COLOR = {index: color for index, color in enumerate(COLORS)}
